# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.10-slim
WORKDIR /app
# Install build dependencies for PEP517
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*
# Copy project
COPY pyproject.toml uv.lock* ./
# Install dependencies
RUN pip install --no-cache-dir .
# Copy remaining source code
COPY . .
# Use a simple command for stdio transport
CMD ["python", "main.py"]
